FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json tsconfig.json turbo.json ./
COPY apps/api-gateway apps/api-gateway
COPY libs libs
COPY prisma prisma

RUN npm ci
RUN npx prisma generate
RUN npm run build --filter=@codex/api-gateway

FROM node:20-alpine AS runner

WORKDIR /app

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nestjs

COPY --from=builder /app/dist/apps/api-gateway ./dist
COPY --from=builder /app/apps/api-gateway/package.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/prisma ./prisma

USER nestjs

EXPOSE 4000

ENV NODE_ENV=production

CMD ["node", "dist/src/main"]
